### ISSUE TITLE
API? Possible to get Sync command?

### ISSUE THREAD

**Issue by momo-the-monster** [soldair/pinoccio-bridge#1]
I can't find where 'command' and 'bridgeCommand' are defined. What's the API for this module? Is it possible to get a sync-stream-style update, or should I continuously poll the scouts?

**Comment by soldair** [comment]
you can bind the data event of the returned stream.
ill whip you up an example. sorry i missed this issue

**Comment by momo-the-monster** [comment]
I'd love to get this up and running tomorrow. Could I see that example?

**Comment by momo-the-monster** [comment]
nevermind, I figured it out:

```
bridge('COM8', {host:localhost'}, function (err, b){
    b.on('data', function(event){
        // Do something with reports
    }
}
```

This works for a while, always stops responding after 30-60 seconds or so.

**Comment by soldair** [comment]
Hmm. And you have the scout going over wifi? I haven't had any issues with
scouts not responding with bridge/ server I'll test today.

**Comment by soldair** [comment]
I'll ping you when I publish the fixes I have been working on. Serial
bridge should be stable.

**Comment by momo-the-monster** [comment]
For this setup, the lead scout is connected via USB, the field scout communicates via radio. I'm able to get a nice stream of messages from the field scout to the lead using the new Shell.eval() function, and then the field scout will stop responding to messages and receiving them, usually after less than a minute. Sometimes its LED will flash green right before it stops responding.
